
SELECT 'CREATE DATABASE simplepdv'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'simplepdv')\gexec

\c simplepdv
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA pdv;

CREATE ROLE sys;
GRANT ALL PRIVILEGES ON DATABASE simplepdv TO sys;
GRANT ALL PRIVILEGES ON SCHEMA pdv TO sys;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pdv TO sys;

CREATE USER pedro WITH PASSWORD 'changeme';
GRANT sys TO pedro;

