CREATE ROLE sys;
GRANT ALL PRIVILEGES ON DATABASE simplepdv TO sys;
GRANT ALL PRIVILEGES ON SCHEMA pdv TO sys;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pdv TO sys;

CREATE USER pedro WITH PASSWORD 'changeme';
GRANT sys TO pedro;

